### ISSUE TITLE
ParseResult problem when importing

### ISSUE THREAD

**Issue by arundurvasula** [kipoi/models#98] opened 2018-06-27 01:38 UTC
Hi! This package looks great! I just installed Kipoi on my Anaconda install (python 3.4.5 on CentOS 6.9). The install finished with no errors, but I am getting the following when I try `import kipoi`:

```
   Traceback (most recent call last):
  File "/u/home/a/arun/anaconda3/bin/kipoi", line 7, in <module>
    from kipoi.__main__ import main
  File "/u/home/a/arun/anaconda3/lib/python3.4/site-packages/kipoi/__init__.py", line 9, in <module>
    from . import config
  File "/u/home/a/arun/anaconda3/lib/python3.4/site-packages/kipoi/config.py", line 13, in <module>
    from .remote import load_source, GitLFSSource, GithubPermalinkSource, LocalSource
  File "/u/home/a/arun/anaconda3/lib/python3.4/site-packages/kipoi/remote.py", line 12, in <module>
    from .components import ModelDescription, DataLoaderDescription
  File "/u/home/a/arun/anaconda3/lib/python3.4/site-packages/kipoi/components.py", line 13, in <module>
    import related
  File "/u/home/a/arun/anaconda3/lib/python3.4/site-packages/related/__init__.py", line 16, in <module>
    from .fields import (
  File "/u/home/a/arun/anaconda3/lib/python3.4/site-packages/related/fields.py", line 2, in <module>
    from future.moves.urllib.parse import ParseResult
ImportError: cannot import name 'ParseResult'
```
Any ideas? Thank you!

**Comment by krrome** [comment] 2018-06-27 07:51
Hi! Thanks for trying out Kipoi. It looks like the `related` package that we are using is causing problems for you. I couldn't reproduce the error you had with python 3.4.5.
In order to say more could you post which commands you used to install Kipoi?

Also, currently we are not testing on python 3.4 - I would recommend installing Kipoi in a *new* environment with python 2.7, python 3.5 or python 3.6. Also consider using our conda installation for Kipoi (https://anaconda.org/bioconda/kipoi).
Let me know if any of that solves your problems.

**Comment by krrome** [comment] 2018-06-27 07:55
This is an issue with the core Kipoi package, I will close the issue here and refer from a new issue in Kipoi/kipoi please continue posting on that one.

**Closed by krrome** 2018-06-27 07:55 UTC
